"""atualiza cadastro de usuario

Revision ID: 54f32854a6c8
Revises: 24c0dc8d0729
Create Date: 2026-09-18 11:13:09.396081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f32854a6c8'
down_revision: Union[str, Sequence[str], None] = '24c0dc8d0729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('instituicao', sa.String(), nullable=False))
    op.add_column('usuarios', sa.Column('data_nasc', sa.Date(), nullable=False))
    op.add_column('usuarios', sa.Column('username', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'usuarios', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'username')
    op.drop_column('usuarios', 'data_nasc')
    op.drop_column('usuarios', 'instituicao')
    # ### end Alembic commands ###
