
export function Index() {

    return (
        <div>
            <h1> OLA USUARIO </h1>
            <h2> DEPOIS PODE BOTAR UM LINK COMO PRÓXIMO QUE AO APERTAR LEVA PRAS PÁGINAS DOS FORMULÁRIOS QUE ELE VAI RESPONDER </h2>
            <h3> AQUI EU ACHO UMA BOA TER UMA PÁGINA DE BOAS VINDAS COM A LOGO E UMA BREVE EXPLICAÇÃO DO QUE RAIOS É LHSA, MESMO QUE O USUÁRIO NÃO VÁ LER, ACHO QUE FICA UM POUCO BONITO </h3>
        </div>
    )
}